package com.floosi.database.seed

import com.floosi.database.entity.CategoryEntity
import com.floosi.database.entity.WalletEntity
import java.math.BigDecimal
import java.time.LocalDateTime
import java.time.ZoneOffset

object SeedData {

    private val now: LocalDateTime = LocalDateTime.now(ZoneOffset.UTC)
    private val nowEpochMillis: Long = now.toInstant(ZoneOffset.UTC).toEpochMilli()

    private fun color(hex: String): Int = android.graphics.Color.parseColor(hex)

    val wallets: List<WalletEntity> = listOf(
        WalletEntity(
            name = "كاش",
            type = "CASH",
            currencyCode = "EGP",
            balance = BigDecimal.ZERO,
            initialBalance = BigDecimal.ZERO,
            color = color("#4CAF50"),
            iconKey = "wallet_cash",
            isArchived = false,
            isExcluded = false,
            sortOrder = 0,
            createdAt = now,
            updatedAt = now,
        ),
        WalletEntity(
            name = "فيزا/ماستر",
            type = "BANK_CARD",
            currencyCode = "EGP",
            balance = BigDecimal.ZERO,
            initialBalance = BigDecimal.ZERO,
            color = color("#2196F3"),
            iconKey = "card",
            isArchived = false,
            isExcluded = false,
            sortOrder = 1,
            createdAt = now,
            updatedAt = now,
        ),
        WalletEntity(
            name = "فودافون كاش",
            type = "VODAFONE_CASH",
            currencyCode = "EGP",
            balance = BigDecimal.ZERO,
            initialBalance = BigDecimal.ZERO,
            color = color("#FF5252"),
            iconKey = "vf_cash",
            isArchived = false,
            isExcluded = false,
            sortOrder = 2,
            createdAt = now,
            updatedAt = now,
        ),
        WalletEntity(
            name = "إنستاباي",
            type = "INSTAPAY",
            currencyCode = "EGP",
            balance = BigDecimal.ZERO,
            initialBalance = BigDecimal.ZERO,
            color = color("#9C27B0"),
            iconKey = "instapay",
            isArchived = false,
            isExcluded = false,
            sortOrder = 3,
            createdAt = now,
            updatedAt = now,
        ),
    )

    val expenseCategories: List<CategoryEntity> = listOf(
        CategoryEntity(
            name = "أكل وشرب",
            type = "EXPENSE",
            iconKey = "food",
            color = color("#FF6B6B"),
            isSystem = true,
            sortOrder = 0,
            keywords = listOf("مطعم", "فطار", "غدا", "عشا", "كافيه"),
            createdAt = now,
            updatedAt = now,
        ),
        CategoryEntity(
            name = "مواصلات",
            type = "EXPENSE",
            iconKey = "directions_car",
            color = color("#4ECDC4"),
            isSystem = true,
            sortOrder = 1,
            keywords = listOf("أوبر", "كريم", "مترو", "بنزين", "توكتوك"),
            createdAt = now,
            updatedAt = now,
        ),
        CategoryEntity(
            name = "سوبر ماركت",
            type = "EXPENSE",
            iconKey = "shopping_cart",
            color = color("#FFA500"),
            isSystem = true,
            sortOrder = 2,
            keywords = listOf("هايبر", "كارفور", "سبينيس", "خير زمان"),
            createdAt = now,
            updatedAt = now,
        ),
        CategoryEntity(
            name = "قهوة",
            type = "EXPENSE",
            iconKey = "local_cafe",
            color = color("#8B4513"),
            isSystem = true,
            sortOrder = 3,
            keywords = listOf("ستاربكس", "كوفي شوب", "بن"),
            createdAt = now,
            updatedAt = now,
        ),
        CategoryEntity(
            name = "فواتير",
            type = "EXPENSE",
            iconKey = "receipt",
            color = color("#9B59B6"),
            isSystem = true,
            sortOrder = 4,
            keywords = listOf("كهربا", "مية", "غاز", "نت"),
            createdAt = now,
            updatedAt = now,
        ),
        CategoryEntity(
            name = "تسوّق",
            type = "EXPENSE",
            iconKey = "shopping_bag",
            color = color("#E91E63"),
            isSystem = true,
            sortOrder = 5,
            keywords = listOf("أمازون", "نون", "جوميا"),
            createdAt = now,
            updatedAt = now,
        ),
        CategoryEntity(
            name = "صحة",
            type = "EXPENSE",
            iconKey = "local_hospital",
            color = color("#00BCD4"),
            isSystem = true,
            sortOrder = 6,
            keywords = listOf("دكتور", "صيدلية", "تحاليل"),
            createdAt = now,
            updatedAt = now,
        ),
        CategoryEntity(
            name = "تعليم",
            type = "EXPENSE",
            iconKey = "school",
            color = color("#3F51B5"),
            isSystem = true,
            sortOrder = 7,
            keywords = listOf("كورس", "كتاب", "جامعة"),
            createdAt = now,
            updatedAt = now,
        ),
        CategoryEntity(
            name = "ترفيه",
            type = "EXPENSE",
            iconKey = "movie",
            color = color("#FF9800"),
            isSystem = true,
            sortOrder = 8,
            keywords = listOf("سينما", "نتفلكس", "شحن"),
            createdAt = now,
            updatedAt = now,
        ),
        CategoryEntity(
            name = "هدوم",
            type = "EXPENSE",
            iconKey = "checkroom",
            color = color("#E91E63"),
            isSystem = true,
            sortOrder = 9,
            keywords = listOf("ملابس", "شوز"),
            createdAt = now,
            updatedAt = now,
        ),
        CategoryEntity(
            name = "تليفون",
            type = "EXPENSE",
            iconKey = "phone_android",
            color = color("#2196F3"),
            isSystem = true,
            sortOrder = 10,
            keywords = listOf("باقات", "شحن", "إنترنت"),
            createdAt = now,
            updatedAt = now,
        ),
        CategoryEntity(
            name = "هوايات",
            type = "EXPENSE",
            iconKey = "palette",
            color = color("#9C27B0"),
            isSystem = true,
            sortOrder = 11,
            keywords = listOf("جيم", "رياضة", "العاب"),
            createdAt = now,
            updatedAt = now,
        ),
        CategoryEntity(
            name = "مصاريف البيت",
            type = "EXPENSE",
            iconKey = "home",
            color = color("#795548"),
            isSystem = true,
            sortOrder = 12,
            keywords = listOf("إيجار", "أثاث", "أدوات"),
            createdAt = now,
            updatedAt = now,
        ),
        CategoryEntity(
            name = "عيلة وأصحاب",
            type = "EXPENSE",
            iconKey = "people",
            color = color("#FFC107"),
            isSystem = true,
            sortOrder = 13,
            keywords = listOf("هدية", "فرح", "عزومة"),
            createdAt = now,
            updatedAt = now,
        ),
        CategoryEntity(
            name = "تاني",
            type = "EXPENSE",
            iconKey = "inventory_2",
            color = color("#607D8B"),
            isSystem = true,
            sortOrder = 14,
            keywords = listOf("مصاريف متفرقة"),
            createdAt = now,
            updatedAt = now,
        ),
    )

    val incomeCategories: List<CategoryEntity> = listOf(
        CategoryEntity(
            name = "مرتب",
            type = "INCOME",
            iconKey = "work",
            color = color("#4CAF50"),
            isSystem = true,
            sortOrder = 0,
            createdAt = now,
            updatedAt = now,
        ),
        CategoryEntity(
            name = "بونص",
            type = "INCOME",
            iconKey = "card_giftcard",
            color = color("#8BC34A"),
            isSystem = true,
            sortOrder = 1,
            createdAt = now,
            updatedAt = now,
        ),
        CategoryEntity(
            name = "فريلانس",
            type = "INCOME",
            iconKey = "laptop",
            color = color("#00BCD4"),
            isSystem = true,
            sortOrder = 2,
            createdAt = now,
            updatedAt = now,
        ),
        CategoryEntity(
            name = "هدية",
            type = "INCOME",
            iconKey = "redeem",
            color = color("#FFC107"),
            isSystem = true,
            sortOrder = 3,
            createdAt = now,
            updatedAt = now,
        ),
        CategoryEntity(
            name = "استثمار",
            type = "INCOME",
            iconKey = "trending_up",
            color = color("#2196F3"),
            isSystem = true,
            sortOrder = 4,
            createdAt = now,
            updatedAt = now,
        ),
        CategoryEntity(
            name = "إيجار",
            type = "INCOME",
            iconKey = "real_estate_agent",
            color = color("#795548"),
            isSystem = true,
            sortOrder = 5,
            createdAt = now,
            updatedAt = now,
        ),
        CategoryEntity(
            name = "تاني",
            type = "INCOME",
            iconKey = "paid",
            color = color("#607D8B"),
            isSystem = true,
            sortOrder = 6,
            createdAt = now,
            updatedAt = now,
        ),
    )

    val allCategories: List<CategoryEntity>
        get() = expenseCategories + incomeCategories
}
